collections:
  archives:
    output: true
  posts:
    output: true
    permalink: /posts/:year/:slug
  recipes:
    output: true

url: "the_sites_url_here.com"
plugins:
  - jekyll-sitemap


_comments:
  title: Max 70 characters
  social_image: Landscape 1200 x 600px
  twitter_card: summary, photo, video, product, app, gallery
  twitter_description: 200 characters